### ISSUE TITLE
colorbar padding is not working for outer top and outer bottom

### ISSUE THREAD

**Issue by sinan0310** [Ultraplot/ultraplot#135]
Hi, I recently explored this project, and it works perfectly, especially for subplots spacing in figures using cartopy projections. My problem is that whether I removed the labels, gridlines, latitude/longitude labels the colorbar pad/space is not working for very small values (e.g. 0.001) for the locations of bottom and top. However, the padding works perfectly fine except bottom and top. I think, some bottom and top labels -does not matter invoked or not- preventing to use padding/spacing for small numbers

Does anyone know solution for this problem? Below you may see the colorbar for bottom and right positions and relevant script.

Thank you in advance!

```python
import xarray as xr
import ultraplot as uplt
import cmaps

df = xr.open_dataset("./PRECIP_daily_CERRA_2021_August.nc")
precip = df["tp"]

fig, ax = uplt.subplot(projection="pcarree",lonlim=(26,45),latlim=(38,50),
                        reso="xx-hi",coast=True,grid=False,figsize=(12,9),
                        coastlinewidth=3,linewidth=3,lonlabels=False,latlabels=False,panelpad=0)
plot = xr.plot.pcolormesh(darray=precip[0,:,:],x="longitude",y="latitude",add_colorbar=False,levels=uplt.arange(10,210,10),cmap=cmaps.WhiteBlueGreenYellowRed,extend="max")
ax.colorbar(plot,loc="r",extend="max",ticklabelsize=16,labelsize=16,space=0.2)
ax.format(title="",titlesize=16)
fig.savefig(f"deneme.png",dpi=300)
``` 

![Image](https://github.com/user-attachments/assets/61f7a71b-6ffe-4780-aecd-12e7798887b0)

![Image](https://github.com/user-attachments/assets/2ef690a3-62d0-4cc2-ac29-adb933615b55)

**Comment by cvanelteren** [comment]
Can you confirm that this issue also occurs with the basemap backend? I can't tackle this problem until next week.

**Comment by sinan0310** [comment]
with basemap the padding works for every location

**Comment by cvanelteren** [comment]
Ok. The cartopy integration is a bit funny as the backend does not entirely make the geoaxes "behave" like a regular axis. For example the "set" commands (x/yticks out of my head) do not always override the same functions as matplotlib. This sometimes causes a disconnect when the we internally call such commands and cartopy not behaving accordingly. Can't look at this until next week but can review code if someone is willing to pick it up.

**Comment by gepcel** [comment]
I guess colorbar size is calculated based on axis size. Geoaxis size maybe a bit difference from regular axis size. Besides figsize and some margin considering,  geoaxis size also depends on specific projection and lonlim and latlim. 

What I used to do with matplotlib and cartopy is after doing all the plottings, call  `plt.draw()` first, and then get axis position, then set the colorbar size and position.

**Comment by cvanelteren** [comment]
> I guess colorbar size is calculated based on axis size. Geoaxis size maybe a bit difference from regular axis size. Besides figsize and some margin considering,  geoaxis size also depends on specific projection and lonlim and latlim. 
> 
> What I used to do with matplotlib and cartopy is after doing all the plottings, call  `plt.draw()` first, and then get axis position, then set the colorbar size and position.

UltraPlot takes care of most of this. I have the suspicion that we are calling the wrong functions that cartopy does not understand. For example in the latest release `Axes.xaxis.set_ticks` are called which under normal mpl would be aliased as `Axes.set_xticks`. From my understanding however cartopy does not provide the same override, meaning `set_xticks` may be defined in cartopy but it does not map to `Axes.xaxis.set_ticks` which diverges from the matplot API. I am expecting that there is a similar discrepancy here with the colorbar. Since the basemap is working it implies some funny things happening with cartopy and how pad the axes.

**Comment by gepcel** [comment]
> UltraPlot takes care of most of this. 

Yes, and I love ultraplot and proplot for that.  For cartopy, the figsize, axis margin and subplot padding are always painful. I'm guessing because the axis can be scaled to fit different fig sizes and margins. But the aspect of geoaxis is fixed for a specific projection and lonlim and latlim.


> From my understanding however cartopy does not provide the same override, meaning set_xticks may be defined in cartopy but it does not map to Axes.xaxis.set_ticks which diverges from the matplot API

Ticks and gridliners are two different things in cartopy. I recall that there are something with cartopy about it like [1117](https://github.com/SciTools/cartopy/pull/1117) and [1089](https://github.com/SciTools/cartopy/pull/1089). Anyway I'm not a developer, just used cartopy for some years.

And about the fig resize, I noticed something I'm not sure if it's worth your attention. Do you use [Positron](https://positron.posit.co/), an IDE for R and python and some others? Ultraplot and proplot don't work in it. Both matplotlib and cartopy work fine. I'm guessing it about some resize thing.

**Comment by cvanelteren** [comment]
I had some time to look at the issue but I cannot reproduce your issue:

![Image](https://github.com/user-attachments/assets/32b26a70-aeb6-44c1-be80-63fee6829946)

```python
import ultraplot as uplt, numpy as np

fig, ax = uplt.subplots(proj="cyl", backend="cartopy")
ax.format(
    land=True,
    toplabelweight="normal",
    latlines=30,
    lonlines=60,
)
norm = uplt.colors.mcolors.Normalize(vmin=0, vmax=1)
h = uplt.colors.mcm.ScalarMappable(norm=norm, cmap="viridis")
ax.colorbar(h, loc="b", extend="max", space=0.2)
ax.colorbar(h, loc="r")

uplt.show(block=1)
```
What am I missing here?

**Comment by cvanelteren** [comment]
Thanks for providing the code. But I still don't see the issue. Locally here it produces the following:

![Image](https://github.com/user-attachments/assets/c148c776-33a6-44bd-b670-8e119b98f125)

What is the version of mpl, ultraplot and cartopy?

**Comment by gepcel** [comment]
OK，now it's strange.

# Image1 with figsize=(12,6)

![Image](https://github.com/user-attachments/assets/902807b6-b032-432f-9378-c947f2152a52)

# Image2 with figsize=(12,12)

![Image](https://github.com/user-attachments/assets/75ffd2bb-5442-49ca-b000-05fca3daea31)

# Image 3

If drop the figsize arg, the right colorbar has the same height as the axis, and the bottom colorbar has the same width as the axis.

![Image](https://github.com/user-attachments/assets/30a66336-44ec-4672-9257-7ed7550d8448)

**Comment by cvanelteren** [comment]
That makes sense. I think this is caused by the auto layout kicking in. You can try adding `fig.auto_layout()` to trigger the layout algorithm. From my understanding setting custom fig sizes does not trigger these, making it more similar to how matplotlib behaves.

**Comment by cvanelteren** [comment]
This seems more of a feature rather than a bug ;-). Is this ok for closing?

**Comment by sinan0310** [comment]
I have also tested plotting without figsize parameter and for now everything seems fine. I am gonna close the issue but I would like to ask for one thing. Could you please add edgecolor for quiver plots? Thanks a lot again to handling the issue
