### ISSUE TITLE
Colormap not using vcenter for pcolormesh/pcolor etc.

### ISSUE THREAD

**Issue by beckermr** [Ultraplot/UltraPlot#313]
ultraplot appears to be ignoring `vmin/vmax`. Further, for some ranges of data inputs, the output plot doesn't use the full range of the color map.

```python
import ultraplot as uplt
import numpy as np

rng = np.random.default_rng(seed=10)
mvals = rng.normal(size=(32, 32))

fig, axs = uplt.subplots(nrows=1, ncols=3, share=0)
for i, ax in enumerate(axs):
    if i == 1 or i == 2:
        vmin = -0.2
        vmax = 2.0
        if i == 2:
            mvals = np.clip(mvals, vmin, vmax)
        cmap = "spectral"
    else:
        cmap = "spectral"
        vmin = None
        vmax = None


    m = ax.pcolormesh(
        mvals,
        cmap=cmap,
        discrete=False,
        vmin=vmin,
        vmax=vmax,
    )
    ax.format(grid=False, xticklabels=[], xticks=[], yticklabels=[], yticks=[])
    ax.colorbar(
        m,
        loc="r",
        label=f"{i}"
    )
```

<img width="2014" height="534" alt="Image" src="https://github.com/user-attachments/assets/4c8eea3d-2a4d-4798-a684-a647774fa2ad" />

**Comment by beckermr** [comment]
cc @cvanelteren 

IDK how we broke this, but it seems like a pretty fundamental issue.

**Comment by beckermr** [comment]
The matplotlib code works as expected:

```python
import matplotlib.pyplot as plt
import numpy as np

rng = np.random.default_rng(seed=10)
mvals = rng.normal(size=(32, 32))

fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(9, 3))
for i, ax in enumerate(axs.ravel()):
    if i == 1 or i == 2:
        vmin = -0.2
        vmax = 2.0
        if i == 2:
            mvals = np.clip(mvals, vmin, vmax)
        cmap = "spectral"
    else:
        cmap = "spectral"
        vmin = None
        vmax = None


    m = ax.pcolormesh(
        mvals,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
    )
    fig.colorbar(
        m,
        ax=ax,
        label=f"{i}"
    )
```

<img width="1800" height="600" alt="Image" src="https://github.com/user-attachments/assets/71afaefd-ce1b-43f2-bb3b-c3b93fd591a0" />

**Comment by cvanelteren** [comment]
Looks the same for me on 157.2 as the one on 1.60.0

**Comment by cvanelteren** [comment]
The docs state: 

> vmin, vmax ([float](https://docs.python.org/3/library/functions.html#float), optional) – The minimum and maximum color scale values used with the norm normalizer. If discrete is False these are the absolute limits, and if discrete is True these are the approximate limits used to automatically determine levels or values lists at “nice” intervals. If levels or values were already passed as lists, these are ignored, and vmin and vmax are set to the minimum and maximum of the lists. If robust was passed, the default vmin and vmax are some percentile range of the data values. Otherwise, the default vmin and vmax are the minimum and maximum of the data values.

setting discrete = True works as expected I think:

<img width="10036" height="2745" alt="Image" src="https://github.com/user-attachments/assets/a04c7842-8ccf-4b17-976e-b7ef32e1b320" />

**Comment by cvanelteren** [comment]
Except for the discreteness ofc, but that is to be expected. The clipping is a bit strange indeed will have a look

**Comment by cvanelteren** [comment]
Ok the issue is in the normalizer I think:

```python
import ultraplot as uplt
import numpy as np

rng = np.random.default_rng(seed=10)
mvals = rng.normal(size=(32, 32))

cmap = "spectral"
norm = uplt.pyplot.cm.colors.Normalize(vmin=-0.2, vmax=2.0)
fig, axs = uplt.subplots(ncols=3, share=0)
for i, ax in enumerate(axs):
    specs = {}
    if i > 0:
        vmin = -0.2
        vmax = 2.0

        specs = dict(norm=norm)
        if i == 2:

            mvals = np.clip(mvals, vmin, vmax)
    m = ax.pcolormesh(
        mvals,
        cmap=cmap,
        discrete=False,
        **specs,
    )
    ax.format(
        grid=False,
        xticklabels=[],
        xticks=[],
        yticklabels=[],
        yticks=[],
    )
    ax.colorbar(m, loc="r", label=f"{i}")
uplt.show(block=1)
```

<img width="1443" height="498" alt="Image" src="https://github.com/user-attachments/assets/0869ff4d-8e42-4f77-8b4a-bc2d1e0ed9dd" />

I traced the vmin and vmax which seems to be fine. 

will fix tomorrow -- can trace the error back to 1.0 (didn't check prior to that)

**Comment by cvanelteren** [comment]
vcenter is set wrong. If I override it in the norm we get:

<img width="1452" height="496" alt="Image" src="https://github.com/user-attachments/assets/a094be0e-bc8d-4199-9451-f2f7b23d06e6" />

**Comment by cvanelteren** [comment]
Fixed on main -- changed title for future reference.

**Comment by beckermr** [comment]
This issue is still not fixed.

```python

import ultraplot as uplt
import numpy as np

rng = np.random.default_rng(seed=10)
mvals = rng.normal(size=(32, 32))

fig, axs = uplt.subplots(nrows=1, ncols=3, share=0)
for i, ax in enumerate(axs):
    if i == 1 or i == 2:
        vmin = -0.2
        vmax = 2.0
        if i == 2:
            mvals = np.clip(mvals, vmin, vmax)
        cmap = "spectral"
    else:
        cmap = "spectral"
        vmin = None
        vmax = None


    m = ax.pcolormesh(
        mvals,
        cmap=cmap,
        discrete=False,
        vmin=vmin,
        vmax=vmax,
    )
    ax.format(grid=False, xticklabels=[], xticks=[], yticklabels=[], yticks=[])
    ax.colorbar(
        m,
        loc="r",
        label=f"{i}"
    )


fig.format(suptitle="ultraplot version: " + uplt.__version__)
```

Same code as before. The output is

<img width="2014" height="575" alt="Image" src="https://github.com/user-attachments/assets/5164580c-3df6-482e-891e-8f9e297c88dd" />

**Comment by beckermr** [comment]
@cvanelteren this is the residual bug I mentioned in another issue involving colormaps and vmin/vmax.

**Comment by beckermr** [comment]
If I set diverging = False, then it all works. I think the code needs to respect vmin, vmax even if it detects diverging data.
